Only dereference arrayref if arrayref
PerlAlien/Alien-Build pull request #243
Opened 2021-01-07 01:08 UTC by zmughal

Otherwise this fails when `@gather` contains a coderef.

2021-01-07 16:16 UTC, plicease requested changes
Please add a test for this.

2021-01-07 16:16 UTC, plicease commented
Please rebase on master to get your CI fix.

2021-01-07 22:43 UTC, zmughal commented
Would you like me to implement the tests through mocking or by setting up an MSYS2 CI workflow (which is what uncovered this for me).

2021-01-08 05:03 UTC, zmughal commented
The build results per commit:

73a5baf

![image](https://user-images.githubusercontent.com/94489/103976464-6a67b080-513c-11eb-96e1-92292f211e30.png)

---

 ef02ae1

![image](https://user-images.githubusercontent.com/94489/103976506-810e0780-513c-11eb-9981-7db3a6fc9c26.png)


---

 f855685

![image](https://user-images.githubusercontent.com/94489/103976525-95520480-513c-11eb-9e2a-d96f9136adbf.png)

2021-01-08 05:42 UTC, zmughal commented
@plicease, it appears that the ` t/test_alien.t` failure is unrelated to this particular fix, but may be a MSYS2/MINGW64-specific thing that needs to be fixed. Not sure why it is failing as I have not had my own use of `Test::Alien` fail like this under MSYS2/MINGW64 before.

2021-01-08 13:25 UTC, plicease commented
> Would you like me to implement the tests through mocking or by setting up an MSYS2 CI workflow with MINGW64 Perl (which is what uncovered this for me).

I was thinking mocks would be fine, but now that we have MSYS2 CI workflow it would be good to figure out why it is failing.

Is this also failing locally?

2021-01-08 20:35 UTC, zmughal commented
Yes, also failing locally. 

![Selection_887](https://user-images.githubusercontent.com/94489/104061526-60869180-51be-11eb-84bb-1d451f8bba9b.png)

2021-01-08 23:27 UTC, zmughal commented
I don't know if this gdb output helps:

![Selection_888](https://user-images.githubusercontent.com/94489/104074830-c121c880-51d6-11eb-9562-37fa26d1d4e3.png)

2021-01-09 03:53 UTC, zmughal commented
I'm not sure if the compiler version might be the issue. I'll try rebuilding MINGW64 Perl.

![Selection_889](https://user-images.githubusercontent.com/94489/104082405-985ffa00-51fb-11eb-835f-d88419fb1f53.png)

2021-01-09 23:08 UTC, plicease commented
I assume you've tried to build/install XS modules?  If not I would doublecheck that works.  Just to make sure this isn't a larger issue with the Perl package.

2021-01-10 00:13 UTC, zmughal commented
My own XS modules work as well as the dependencies of Dist::Zilla (Moose).

I could create a branch with the CI workflow testing a single XS module just to make sure.

2021-01-10 01:33 UTC, zmughal commented
One thing I noticed is that ExtUtils::CBuilder uses an explicit address for the image-base <https://metacpan.org/source/AMBS/ExtUtils-CBuilder-0.280235/lib/ExtUtils/CBuilder/Platform/Windows/GCC.pm#L75> while EUMM uses enable-auto-image-base <https://metacpan.org/source/BINGOS/ExtUtils-MakeMaker-7.58/lib/ExtUtils/MM_Win32.pm#L312>.

Will check once I get back to my desk.

2021-01-10 02:17 UTC, plicease commented
> One thing I noticed is that ExtUtils::CBuilder uses an explicit address for the image-base https://metacpan.org/source/AMBS/ExtUtils-CBuilder-0.280235/lib/ExtUtils/CBuilder/Platform/Windows/GCC.pm#L75 while EUMM uses enable-auto-image-base https://metacpan.org/source/BINGOS/ExtUtils-MakeMaker-7.58/lib/ExtUtils/MM_Win32.pm#L312.
> 
> Will check once I get back to my desk.

Interesting!  I think we can add flags to CBuilder (what we use for Test::Alien) so if that makes a difference we might be able to add that flag for msys2-mingw assuming we can detect that. I'd rather not change the behavior for Strawberry.

2021-01-10 05:02 UTC, zmughal commented
Looks like that was it!

The following error for `t/test_alien.t` (which I am copying here for searchability):

```
2021-01-08T04:57:17.4762296Z         # Failed test 'xs'
2021-01-08T04:57:17.4762885Z         # at t/test_alien.t line 518.
2021-01-08T04:57:17.4763347Z         #   XSLoader failed
2021-01-08T04:57:17.4764368Z         #     Can't load 'D:\a\_temp\msys\msys64\tmp\test-alien-EdfFkA/auto/Test/Alien/XS/Mod1/Mod1.dll' for module Test::Alien::XS::Mod1: load_file:Invalid access to memory location at D:/a/_temp/msys/msys64/mingw64/lib/perl5/core_perl/DynaLoader.pm line 193.
2021-01-08T04:57:17.4765472Z         # � at t/test_alien.t line 509.
2021-01-08T04:57:17.4766136Z         # Compilation failed in require at D:\a\Alien-Build\Alien-Build\.build\3SLA83oX6v\blib\lib/Test/Alien.pm line 414.
2021-01-08T04:57:17.4767071Z         # BEGIN failed--compilation aborted at D:\a\Alien-Build\Alien-Build\.build\3SLA83oX6v\blib\lib/Test/Alien.pm line 414.
2021-01-08T04:57:17.4767736Z     # Failed test 'with xs_load'
```

goes away with this patch that removes the explicit image-base address and instead uses `enable-auto-image-base`:

<https://github.com/zmughal/p5-Alien-Build/compare/fix/pkgconf-cli-mingw-arrayref...zmughal:mingw-patch-cbuilder-image-base> which I ran here <https://github.com/zmughal/p5-Alien-Build/runs/1675646593?check_suite_focus=true>

```
          perl -pi -e 'my $im = q/-Wl,--image-base,$spec{image_base}/; s/\Q$im\E/-Wl,--enable-auto-image-base/' $( perl -MExtUtils::CBuilder::Platform::Windows::GCC -E 'say $INC{"ExtUtils/CBuilder/Platform/Windows/GCC.pm"}' )
```

![image](https://user-images.githubusercontent.com/94489/104114846-8438fd00-52ce-11eb-9ebc-a5637284088b.png)

2021-01-10 07:49 UTC, zmughal commented
@plicease, I don't think it will be possible to patch the linker command without patching `ExtUtils::CBuilder` itself. If I pass in a config via `lddlflags`, the explicit image-base address will still be in the linker command which means it still will fail to load the DLL under MSYS2/MINGW Perl as seen here: <https://github.com/zmughal/p5-Alien-Build/compare/fix/pkgconf-cli-mingw-arrayref...zmughal:mingw-config-cbuilder-image-base>, <https://github.com/zmughal/p5-Alien-Build/runs/1675965308?check_suite_focus=true>

I agree that this should not be done for Strawberry Perl. I believe the reason why Strawberry Perl and MSYS2/MINGW are different is because they have different defaults and different versions of GNU Binutils (Strawberry: 2.32, MSYS2/MINGW: 2.35.1). There is more discussion about the linker settings for MSYS2/MINGW here: <https://github.com/msys2/MINGW-packages/issues/6674>.

I'm also coming across an issue when I run `while true; do prove -l t/test_alien.t; done` after applying the `--enable-auto-image-base` patch on MSYS2/MINGW. The test intermittently fails with the same `load_file:Invalid access to memory location` error message, but only on one of the module DLLs being loaded instead of all of them and a random one each time and this failure is at random intervals. That does not seem acceptable and I'm wondering if there is an alternative set of linker flags which are needed.

2021-01-10 10:58 UTC, zmughal commented
An alternative that does not have the problem of intermittent failure as mentioned above for `--enable-auto-image-base` is to use the linker settings used by MSYS2/MINGW64 for creating packages which are located in [`/etc/makepkg_mingw64.conf`](https://github.com/msys2/MSYS2-packages/blob/a5855c6458afc6a62628af2ef2a8d5db2d636637/pacman/makepkg_mingw64.conf#L62).

<https://github.com/zmughal/p5-Alien-Build/compare/fix/pkgconf-cli-mingw-arrayref...zmughal:mingw-patch-cbuilder-conf-flags>, <https://github.com/zmughal/p5-Alien-Build/runs/1676236887>

```diff
+          perl -pi -e 'my $im = q/-Wl,--image-base,$spec{image_base}/; s/\Q$im\E/-Wl,--dynamicbase,--high-entropy-va,--nxcompat,--default-image-base-high/' $( perl -MExtUtils::CBuilder::Platform::Windows::GCC -E 'say $INC{"ExtUtils/CBuilder/Platform/Windows/GCC.pm"}' )
```

---

Perhaps the fix for `ExtUtils::CBuilder` should be that it should not add `-Wl,--image-base` when there are flags in `lddlflags` which conflict with using an explicit address.

2021-01-11 17:13 UTC, plicease commented
Okay so I don't think the bug here is in `Test::Alien` or `Alien::Build`.  I'd be curious if MB + XS modules fail if at least intermittently since MB I believe is using CBuilder.  The test suite for AB will fail more reliably since it does the compile+link several times.  I think the root purpose of this PR should be applied though, so maybe the best course of action is:

 1. patch CBuilder in the MSYS2 + mingw workflow.  Please add a comment in the .yml file that points to this discussion 
 2. once it passes merge this PR
 3. report this to CBuilder with suggestions.  Probably worth seeing if MB + XS can reproduce this at all.

2021-01-11 17:17 UTC, plicease commented
@zmughal thanks for doing a lot of research + experimentation on this :+1:

2021-01-11 20:08 UTC, zmughal commented
I have figured out the cause of the different behaviours. It's the generated module names!

I noticed that `ExtUtils::CBuilder` was doing [hashing](https://metacpan.org/source/AMBS/ExtUtils-CBuilder-0.280235/lib/ExtUtils/CBuilder/Platform/Windows/GCC.pm#L49) to obtain the image-base address and that they were all the same in the build output (non-patched):
```
Mod0.dll" -Wl,--image-base,0x630b0000
Mod1.dll" -Wl,--image-base,0x630b0000
Mod2.dll" -Wl,--image-base,0x630b0000
Mod3.dll" -Wl,--image-base,0x630b0000
```

This is because it only uses the basename for the hashing, but also because the hash function only uses 8 chars of data from that basename. This is why loading all these modules in the same `perl` interpreter fails. So if modules that were using the name `.../XS.dll` were built this way by `ExtUtils::CBuilder`, they would face the same problem, but also if it switched to a full module name, a shared prefix would cause the same problem. The changelog of `EU::MM` also notes this about the same hash function which it used in the past <https://github.com/Perl-Toolchain-Gang/ExtUtils-MakeMaker/commit/343d21a453c4d03cf7304dbd4c4dd8180df574ad>.

The `--enable-auto-image-base` option for `ld` also does something similar, but has a [hash function `strhash`](https://sourceware.org/git/?p=binutils-gdb.git;a=blob;f=ld/emultempl/pep.em;hb=binutils-2_35_1#l850) that uses all the characters in the output filename argument. This is likely colliding despite the different temporary directory names, so that might be why it has intermittent failures. This is what [`EU::MM` does now](https://metacpan.org/source/BINGOS/ExtUtils-MakeMaker-7.58/lib/ExtUtils/MM_Win32.pm#L312) as mentioned previously.

Using ASLR via the `--dynamicbase` ld option as in `makepkg_mingw64.conf` works in every case and has security benefits, but I'm not sure if that is ready to use by everything downstream (both MINGW packages and Perl distributions). This is worth running tests across CPAN.

---

A possible fix (tested [1 - patch](https://github.com/zmughal/p5-Alien-Build/runs/1679077246?check_suite_focus=true), [2 - loop](https://github.com/zmughal/p5-Alien-Build/runs/1683490089?check_suite_focus=true)) is to change the way module names are generated

<https://github.com/zmughal/p5-Alien-Build/compare/fix/pkgconf-cli-mingw-arrayref...zmughal:module-name-image-base>

```diff
-    my $name = sprintf "Test::Alien::XS::Mod%s", $count++;
+    my $name = sprintf "Test::Alien::XS::Mod%s%s", $count, chr(65 + $count % 26 ) x 4;
+    $count++;
```

This does not require a patch to `ExtUtils::CBuilder` and generates unique addresses:

```perl
my %hashes;
for my $n (0..64) {
	#my $name = sprintf "Mod%s.dll", $n; # original
	my $name = sprintf "Mod%s%s.dll", $n, chr(65 + $n % 26 ) x 4;
	$name =~ /(....)(.{0,4})/;
	my $addr = sprintf( "0x%x0000", unpack('n', $1 ^ $2) );
	die "Hash $addr for $name already exists" if exists $hashes{$addr};
	$hashes{$addr} = 1;
}
print "All unique\n";
```

I would recommend this last fix for now and let `EU::CBuilder` know about the issue with the hash function.

2021-01-11 20:38 UTC, plicease commented
> I would recommend this last fix for now and let `EU::CBuilder` know about the issue with the hash function.

Okay.  Sounds good to me.

2021-01-11 21:10 UTC, plicease approved these changes

2021-01-11 21:10 UTC, merged

2021-01-11 21:38 UTC, plicease commented
Released as 2.38.

2021-02-14 05:04 UTC, zmughal commented
The changes to image-base generation submitted to Perl are now in [ExtUtils-CBuilder-0.280236](https://metacpan.org/release/AMBS/ExtUtils-CBuilder-0.280236).